# configuration for connecting to the sql database.
# ---
# host should be a file path if connecitng via a UNIX socket or an ip adress/url ir connecting to a remote session.
host = "/run/postgresql/"  
user = "postgres"
# passwd = "super_secret_password" # only needed if you dont have passwordless auth on the database.
# port = "5432"
# ssl_cert = "/path/to/ca_cert_file.cert"  # if you're running postgres locally this is unnessesary. comment this out if you wish to not use ssl. 
# template_db = "ptdb-template"
require_ssl = false