[package]
name = "ptdb"
version = "0.3.10"
edition = "2021"

# See more keys and their definitions at:
# https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "workspaces/config",
    "workspaces/graphql",
    "workspaces/sql",
    "workspaces/ptdb_lib",
]

[dependencies]
# postgres = "0.19.3"
shellexpand = "2.1.0"
clap = { version = "4.0.9", features = ["unstable-grouped"] }
toml = "0.5.9"
# strip-ansi-escapes = "0.1.1"
prettytable-rs = "^0.9"
# dns-lookup = "1.0.8"
config = { path = "workspaces/config" }
graphql = { path = "workspaces/graphql" }
sql = { path = "workspaces/sql" }
ptdb_lib = { path = "workspaces/ptdb_lib" }
db_com = { path = "workspaces/db_common" }