[package]
name = "PenTestDB"
version = "0.1.0"
edition = "2021"

# client used to control the server
[[bin]]
name = "ptdb"
path = "src/ptdb/main.rs"

# runs in the backgorund as a server. it collects the data from pt-gather and
# stores it in the data base.
[[bin]]
name = "ptdb-server"
path = "src/ptdb-server/main.rs"

# used to gather data for a single command.
[[bin]]
name = "ptdb-gather"
path = "src/ptdb-gather/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
configparser = "3.0.0"
shellexpand = "2.1.0"
