[package]
name = "ptdb"
version = "0.3.10"
edition = "2021"

# See more keys and their definitions at:
# https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ptdb"
path = "./src/lib.rs"

[[bin]]
name = "ptdb"
path = "./src/bin/ptdb.rs"

# [workspace]
# members = [
#     # "workspaces/config",
#     # "workspaces/db_common",
#     # "workspaces/graphql",
#     # "workspaces/sql",
#     # "workspaces/ptdb_lib",
# ]

[dependencies]
shellexpand = "2.1.0"
clap = { version = "4.0.9", features = ["unstable-grouped"] }
toml = "0.5.9"
# strip-ansi-escapes = "0.1.1"
prettytable-rs = "^0.9"
log = { version = "0.4.19", features = ["release_max_level_warn", "max_level_trace"] }
simple_logger = "4.2.0"
serde = { version = "1.0", features = ["derive"] }
figment = { version = "0.10", features = ["toml"] }
tabled = "0.10"
reqwest = { version = "0.11", features = ["blocking"] }
postgres = "0.19.3"
openssl = "0.10.38"
postgres-openssl = "0.5.0"
chrono = "0.4"
serde_json = "1.0"
dns-lookup = "1.0.8"