[package]
name = "PenTestDB"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at:
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shellexpand = "2.1.0"
serde = { version = "1.0", features = ["derive"] }
figment = { version = "0.10", features = ["toml"] }
postgres = "0.19.3"
# config-file = "0.2.3"
openssl = "0.10.38"
postgres-openssl = "0.5.0"
chrono = "0.4"
