[package]
name = "PenTestDB"
version = "0.1.0"
edition = "2021"

# # the client used to control the server and gatherer
# [[bin]]
# name = "ptdb"
# path = "src/bin/ptdb.rs"
#
# # runs in the backgorund as a server. it collects the data from pt-gather and
# # stores it in the data base.
# [[bin]]
# name = "ptdb-server"
# path = "src/bin/ptdb-server.rs"

# # used to gather data for a single command.
# [[bin]]
# name = "ptdb-gather"
# path = "src/bin/ptdb-gather/main.rs"

# [lib]
# name = "cmd-parser"
# path = "src/lib/cmd-parser.rs"

# See more keys and their definitions at:
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shellexpand = "2.1.0"
serde = { version = "1.0", features = ["derive"] }
config-file = "0.2.3"
# ptyprocess = "0.3.0"
# makepty = { git = "https://github.com/tmsbrg/makepty.git" }
# portable-pty = "0.7.0"
# io-streams = "0.4.2"
# nix = "0.24.2"
# term_size = "0.3.2"
# system-interface = "0.21.0"
# cmd-parser = { path = "src/lib/cmd-parser.rs" }
