version: "3.8"
services:
  database:
    # build: tests/postgres-docker/.
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    user: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 1s
      timeout: 3600s
      retries: 24
  target:
    # image: "python:3.10-bullseye"
    build: tests/target-docker/.
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 1s
      timeout: 3600s
      retries: 24
  ptdb-test:
    build: .
    # tty: true
    volumes:
      # - ./tests/db-output/:/root/code/tests/db-output/:rw
      - ./src:/root/code/src:ro
      - ./workspaces:/root/code/workspaces:ro
      - ./target/debug:/root/code/target/debug:rw
      - ./Cargo.toml:/root/code/Cargo.toml:ro
      - ./tests/test.sh:/root/code/tests/test.sh:ro
      - ./configs/etc/ptdb/parsers/:/etc/ptdb/parsers/:ro
      - ./configs/.config/ptdb/:/root/.config/ptdb/:rw
    environment:
      TARGET_IP: pentestdb-target-1
      DB_IP: pentestdb-database-1
      psql_user: postgres
      psql_pass: postgres
      DB_NAME: docker
    depends_on:
      target:
        condition: service_healthy
      database:
        condition: service_healthy