[package]
name = "graphql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shellexpand = "2.1.0"
postgres = "0.19.3"
openssl = "0.10.38"
postgres-openssl = "0.5.0"
chrono = "0.4"
serde_json = "1.0"
config = { path = "../config" }
reqwest = { version = "0.11", features = ["blocking"] }
prettytable-rs = "^0.9"
