[package]
name = "sql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettytable-rs = "^0.9"
postgres = "0.19.3"
openssl = "0.10.38"
postgres-openssl = "0.5.0"
shellexpand = "2.1.0"
config = { path = "../config" }
db_com = { path = "../db_common" }
