host_id = ["ip", "ipv6", "dns_name"]  # ways to find a host in the hosts database don't mess with this.
port_id = ["port"]
sql_null_val = "''"

# defines what sql columns are in what tables in the sql database. 
# difining things in this config file will make it easier to change the structure of the 
# database later on down the line.
[sql_tables]
ip = "hosts"
ipv6 = "hosts"
dns_name = "hosts"
local_name = "hosts"
gateway_to = "hosts"
gateway_from = "hosts"
port = "ports"
TL_protocol = "ports"
service = "ports"
version = "ports"
state = "ports"
web_protocol = "web_dirs"
res_code = "web_dirs"
base_url = "web_dirs"
url = "web_dirs"
method = "web_dirs"
redirect_adr = "web_dirs"
dir = "web_dirs"
num_chars = "web_dirs"
command = "commands"
hash_file = "creds"
wordlist = "creds"
username = "creds"
password = "creds"
domain = "creds"

# this defines when ptdb will revise a row in a database or make a new one.   
[overlap]
hosts = "local_name OR ip AND dns_name OR ipv6 AND dns_name"
ports = "host_uid AND port AND TL_protocol"
web_dirs = "url OR dir AND host_uid AND base_url" # rows are same if (url match OR dir match AND host_uid match AND base_url matches)
creds = "host_uid AND username AND password AND domain"

