host_id = ["ip", "ipv6", "dns_name"]  # ways to find a host in the machines database don't mess with this.
port_id = ["port"]
sql_null_val = "''"

# defines what sql columns are in what tables in the sql database. 
# difining things in this config file will make it easier to change the structure of the 
# database later on down the line.
[sql_tables]
ip = "machines"
ipv6 = "machines"
dns_name = "machines"
local_name = "machines"
gateway_to = "machines"
mac_adr = "machines"
# gateway_from = "machines"
port = "ports"
TL_protocol = "ports"
service = "ports"
version = "ports"
state = "ports"
web_protocol = "web_dirs"
res_code = "web_dirs"
base_url = "web_dirs"
url = "web_dirs"
method = "web_dirs"
redirect_adr = "web_dirs"
dir = "web_dirs"
num_chars = "web_dirs"
command = "commands"
hash_file = "creds"
wordlist = "creds"
username = "creds"
password = "creds"
domain = "creds"
cname = "cnames"
points_to = "cnames"
# dns_name = "dns_names"


# this defines when ptdb will revise a row in a database or make a new one.   
[overlap]
machines = "ip OR ipv6 OR mac_adr OR dns_name_uid"
ports = "machine_uid AND port AND TL_protocol"
web_dirs = "url OR dir AND machine_uid AND base_url" # rows are same if (url match OR dir match AND machine_uid match AND base_url matches)
creds = "machine_uid AND username AND password AND domain"
dns_names = "dns_name"

