version: "3.8"
services:
  database:
    # build: tests/postgres-docker/.
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    user: postgres
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 1s
      timeout: 3600s
      retries: 24
  target:
    # image: "python:3.10-bullseye"
    build: ../tests/target-docker/.
    ports:
      - "127.0.0.1:8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 1s
      timeout: 3600s
      retries: 24
    # ptdb-test:
    #   build: .
    #   tty: true
    #   stdin_open: true
    #   volumes:
    #     - ../tests/db-output/:/root/code/tests/db-output/:rw
    #     - ../src:/root/code/src:ro
    #     - ../Cargo.toml:/root/code/Cargo.toml:ro
    #     - ../tests/test.sh:/root/code/tests/test.sh:ro
    #     - ../tests/test-scripts:/root/code/tests/test-scripts:ro
    #     - ../tests/db-output:/root/code/tests/db-output:rw
    #     - ../configs/etc/ptdb/parsers/:/etc/ptdb/parsers/:ro
    #     - ../configs/etc/ptdb/make-db.sql:/etc/ptdb/make-db.sql:ro
    #     - ../configs/etc/ptdb/config.toml:/etc/ptdb/config.toml:ro
    #     - ../configs/.config/ptdb/:/root/.config/ptdb/:rw
    #     - ../configs/etc/ptdb/templates.toml:/etc/ptdb/templates.toml:ro
    #     - ./ptdb_start.sh:/root/.ptdb_start.sh:ro
    #     - ./demo.toml:/root/.config/ptdb/db-servers/demo.toml:ro
    #     - ./engagement.toml:/root/.config/ptdb/engagement.toml:ro
    #     # - ../target/release/ptdb:/bin/ptdb:ro
    # environment:
    #   TARGET_IP: pentestdb-target-1
    #   DB_IP: pentestdb-database-1
    #   psql_user: postgres
    #   psql_pass: postgres
    #   DB_NAME: docker
    # depends_on:
    #   target:
    #     condition: service_healthy
    #   database:
    #     condition: service_healthy
