engagement_conf = "engagement.toml"

[sql]
host = "/run/postgresql/"  # "localhost"
user = "postgres"
# passwd = "super_secret_password" # only needed if you dont have passwordless auth on the database.
port = "5432"
ssl = false
cert = "/path/to/ca_cert_file.cert"

# config file for all PenTestDB commands
[server]
socket = "/tmp/ptdb/server"
local_mode = true
ssh_mode = true
ftp_mode = true

[[parser.feroxbuster]]
parser = "feroxbuster.parser"

[[parser.rustscan]]
parser = "rustscan.parser"

[[parser.gobuster]]
parser = "gobuster.parser"

[[parser.searchsploit]]
parser = "searchsploit.parser"

[parser.john]
parser = "john.parser"

[[parser.hydra]]
parser = "hydra.parser"

[[parsers.nmap]]
parser = "nmap/base-nmap.parser"

[[parsers.cat]]
parser = "nmap/base-nmap.parser"

[[parsers.nmap]]
# each sub-array in args is one set of arguments, ALL of which must be present,
# OR ALL of any other sub-list muct be present, for this parser to be used to.
# so this parser will be used, ONLY if the user call nmap, AND either `--script=vuln`
# is on of the args to Nmap, or if both `--script` and `vuln` are both present
# in the args list.
#
# to put it in quazi-math syntaxt:
# args[0][0] AND ... AND args[0][n] OR ... OR args[k][0] AND ... AND args[k][n]
args = [['--script=vuln'],
        ['--script', 'vuln']]
parser = "nmap/nmap-vuln.parser"
