engagement_conf = "engagement.toml"

# config file for all PenTestDB commands
[server]
socket = "/tmp/ptdb/server"
local_mode = true
ssh_mode = true
ftp_mode = true
parser_dir = "/home/yogurt/Code/misc/PenTestDB/configs/.config/ptdb/parsers/"  # "~/.local/ptdb/parsers/"
# commands = ["nmap","feroxbuster","gobuster","rustscan","searchsploit","john","hydra"]
# planned for the future: aircrack-ng,sqlmap,wfuzz,ffuf

[parsers]
# parsers-dir = "/etc/ptdb/parsers/"
nmap = "nmap.parser"
cat = "nmap.parser"
feroxbuster = "feroxbuster.parser"
gobuster = "gobuster.parser"
rustscan = "rustscan.parser"
searchsploit = "searchsploit.parser"
john = "john.parser"
hydra = "hydra.parser"
