active = true

[server_mode]
socket_adr = "/tmp/ptdb/server"
quiet_logs = false  # same effect as the '-q' flag for the parse subcmd but for the server specifically.

[targets]
hosts = "FROM machines JOIN dns_names ON machines.id = dns_names.machine_uid JOIN ports ON machines.id = ports.machine_uid"
machines = "FROM machines Join dns_names ON machines.id = dns_names.machine_uid"
ports = "FROM ports JOIN machines ON machines.id = ports.machine_uid JOIN commands ON ports.command_uid = commands.id"
web_dirs = "FROM web_dirs JOIN machines ON machines.id = web_dirs.machine_uid JOIN commands ON web_dirs.command_uid = commands.id"
web-dirs = "FROM web_dirs JOIN machines ON machines.id = web_dirs.machine_uid JOIN commands ON web_dirs.command_uid = commands.id"
wd = "FROM web_dirs JOIN machines ON machines.id = web_dirs.machine_uid JOIN commands ON web_dirs.command_uid = commands.id"
creds = "FROM creds JOIN commands ON creds.command_uid = commands.id"
credentials = "FROM creds JOIN commands ON creds.command_uid = commands.id"
dns_names = "FROM dns_names JOIN machines ON dns_names.machine_uid = machines.id"
CREDENTIALS = "FROM creds"
WEB_DIRS = "FROM web_dirs"
HOSTS = "FROM machines"
COMMANDS = "FROM commands"
CMDS = "FROM commands"
DNS_NAMES = "FROM dns_names"
MACHINES = "FROM machines"

[[parsers.feroxbuster]]
parser = "feroxbuster.py"

[[parsers.rustscan]]
parser = "rustscan.py"
parse_on_error = false  # default is true so this option is only nessesary if you what the parser to NOT parse of errors.

[[parsers.gobuster]]
parser = "gobuster.py"
args = [["dir"]]
help = ["-h", "--help", "help"]  # default is ["-h", "--help"] so this option is only nessesary if there are other/different help arguments

[[parsers.john]]
parser = "john.py"
help = ["-h", "--help"]

[[parsers.john]]
parser = "john_show.py"
args = [['--show']]

[[parsers.nmap]]
parser = "base_nmap.py"

[[parsers.hydra]]
parser = "hydra.py"

# [[parsers.cat]]
# parser = "hydra.py"
# help = ["-h", "--help"]

[[parsers.fping]]
parser = "fping.py"

[[parsers.dig]]
parser = "dig.py"

[[parsers.nmap]]
# each sub-array in args is one set of arguments, ALL of which must be present,
# OR ALL of any other sub-list muct be present, for this parser to be used to.
# so this parser will be used, ONLY if the user call nmap, AND either `--script=vuln`
# is on of the args to Nmap, or if both `--script` and `vuln` are both present
# in the args list.
#
# to put it in quazi-math syntaxt:
# (args[0][0] AND ... AND args[0][n]) OR ... OR (args[k][0] AND ... AND args[k][n])
args = [['--script=vuln'],
        ['--script', 'vuln']]
parser = "nmap/nmap-vuln.parser"
